markdown: kramdown

collections:
  screenshots:
    output: true
    permalink: /desktop/screenshots/:name
  cloud_pricing:
    output: true
    permalink: /cloud/pricing/:name
  server_pricing:
    output: true
    permalink: /server/pricing/:name
  themes:
    output: true
  guides:
    output: true